2025-08-17T02:10:19.3779375Z ##[group]Run actions/setup-python@v5
2025-08-17T02:10:19.3779899Z with:
2025-08-17T02:10:19.3780080Z   python-version: 3.11
2025-08-17T02:10:19.3780269Z   cache: pip
2025-08-17T02:10:19.3780485Z   cache-dependency-path: requirements-dev.txt

2025-08-17T02:10:19.3780766Z   check-latest: false
2025-08-17T02:10:19.3781073Z   token: ***
2025-08-17T02:10:19.3781262Z   update-environment: true
2025-08-17T02:10:19.3781475Z   allow-prereleases: false
2025-08-17T02:10:19.3781674Z   freethreaded: false
2025-08-17T02:10:19.3781846Z env:
2025-08-17T02:10:19.3782006Z   PG_USER: postgres
2025-08-17T02:10:19.3782178Z   PG_PASSWORD: pass
2025-08-17T02:10:19.3782352Z   PG_DATABASE: awa
2025-08-17T02:10:19.3782718Z   PG_HOST: localhost
2025-08-17T02:10:19.3782892Z   PG_PORT: 5432
2025-08-17T02:10:19.3783271Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-17T02:10:19.3783673Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-17T02:10:19.3784052Z   DATABASE_URL: ***localhost:5432/awa
2025-08-17T02:10:19.3784275Z   DATA_DIR: /tmp/awa-data
2025-08-17T02:10:19.3784491Z   ENABLE_LIVE: 0
2025-08-17T02:10:19.3784668Z   TESTING: 1
2025-08-17T02:10:19.3784830Z ##[endgroup]
2025-08-17T02:10:19.5432158Z ##[group]Installed versions
2025-08-17T02:10:19.6003880Z Successfully set up CPython (3.11.13)
2025-08-17T02:10:19.6004435Z ##[endgroup]
2025-08-17T02:10:19.6365267Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-17T02:10:21.2356023Z /home/runner/.cache/pip
2025-08-17T02:10:21.3743894Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
2025-08-17T02:10:22.3904225Z Received 203535974 of 203535974 (100.0%), 202.2 MBs/sec
2025-08-17T02:10:22.3906955Z Cache Size: ~194 MB (203535974 B)
2025-08-17T02:10:22.4021197Z [command]/usr/bin/tar -xf /home/runner/work/_temp/8d848a5e-d897-45fc-a024-7f116c40a2ed/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-17T02:10:22.7397834Z Cache restored successfully
2025-08-17T02:10:22.7785917Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
