2025-08-17T15:18:04.0743983Z ##[group]Run actions/setup-python@v5
2025-08-17T15:18:04.0744272Z with:
2025-08-17T15:18:04.0744448Z   python-version: 3.11
2025-08-17T15:18:04.0744642Z   cache: pip
2025-08-17T15:18:04.0744856Z   cache-dependency-path: requirements-dev.txt

2025-08-17T15:18:04.0745129Z   check-latest: false
2025-08-17T15:18:04.0745445Z   token: ***
2025-08-17T15:18:04.0745639Z   update-environment: true
2025-08-17T15:18:04.0745856Z   allow-prereleases: false
2025-08-17T15:18:04.0746075Z   freethreaded: false
2025-08-17T15:18:04.0746250Z env:
2025-08-17T15:18:04.0746409Z   PG_USER: postgres
2025-08-17T15:18:04.0746589Z   PG_PASSWORD: pass
2025-08-17T15:18:04.0746757Z   PG_DATABASE: awa
2025-08-17T15:18:04.0746945Z   PG_HOST: localhost
2025-08-17T15:18:04.0747120Z   PG_PORT: 5432
2025-08-17T15:18:04.0747493Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-17T15:18:04.0747884Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-17T15:18:04.0748258Z   DATABASE_URL: ***localhost:5432/awa
2025-08-17T15:18:04.0748487Z   DATA_DIR: /tmp/awa-data
2025-08-17T15:18:04.0748727Z   ENABLE_LIVE: 0
2025-08-17T15:18:04.0748895Z   TESTING: 1
2025-08-17T15:18:04.0749054Z ##[endgroup]
2025-08-17T15:18:04.2404436Z ##[group]Installed versions
2025-08-17T15:18:04.2527539Z Successfully set up CPython (3.11.13)
2025-08-17T15:18:04.2528246Z ##[endgroup]
2025-08-17T15:18:04.2900293Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-17T15:18:05.6663699Z /home/runner/.cache/pip
2025-08-17T15:18:05.7809974Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-2005571a326e80fd181d633d96bfcc1ae8cb53ffd7b38d40aba6418cea7f5ab1
2025-08-17T15:18:06.8730411Z Received 230957298 of 230957298 (100.0%), 211.6 MBs/sec
2025-08-17T15:18:06.8732565Z Cache Size: ~220 MB (230957298 B)
2025-08-17T15:18:06.8769026Z [command]/usr/bin/tar -xf /home/runner/work/_temp/6ccf0c23-1c5f-429e-bcae-c1e264360e72/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-17T15:18:07.3087655Z Cache restored successfully
2025-08-17T15:18:07.3521413Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-37c9ce054bf8aec7fb9f1b24cb0b7760d658659de5ba6816a1006b9693ca1c25
