2025-08-17T12:43:02.8052829Z ##[group]Run actions/setup-python@v5
2025-08-17T12:43:02.8053156Z with:
2025-08-17T12:43:02.8053357Z   python-version: 3.11
2025-08-17T12:43:02.8053573Z   cache: pip
2025-08-17T12:43:02.8053820Z   cache-dependency-path: requirements-dev.txt

2025-08-17T12:43:02.8054353Z   check-latest: false
2025-08-17T12:43:02.8054701Z   token: ***
2025-08-17T12:43:02.8054905Z   update-environment: true
2025-08-17T12:43:02.8055154Z   allow-prereleases: false
2025-08-17T12:43:02.8055389Z   freethreaded: false
2025-08-17T12:43:02.8055591Z env:
2025-08-17T12:43:02.8055771Z   PG_USER: postgres
2025-08-17T12:43:02.8055972Z   PG_PASSWORD: pass
2025-08-17T12:43:02.8056177Z   PG_DATABASE: awa
2025-08-17T12:43:02.8056373Z   PG_HOST: localhost
2025-08-17T12:43:02.8056582Z   PG_PORT: 5432
2025-08-17T12:43:02.8057032Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-17T12:43:02.8057466Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-17T12:43:02.8057921Z   DATABASE_URL: ***localhost:5432/awa
2025-08-17T12:43:02.8058180Z   DATA_DIR: /tmp/awa-data
2025-08-17T12:43:02.8058439Z   ENABLE_LIVE: 0
2025-08-17T12:43:02.8058629Z   TESTING: 1
2025-08-17T12:43:02.8058802Z ##[endgroup]
2025-08-17T12:43:02.9931089Z ##[group]Installed versions
2025-08-17T12:43:03.0016068Z Successfully set up CPython (3.11.13)
2025-08-17T12:43:03.0016993Z ##[endgroup]
2025-08-17T12:43:03.0332932Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-17T12:43:06.3813929Z /home/runner/.cache/pip
2025-08-17T12:43:06.4810279Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
2025-08-17T12:43:07.4937551Z Received 203535974 of 203535974 (100.0%), 199.5 MBs/sec
2025-08-17T12:43:07.4939988Z Cache Size: ~194 MB (203535974 B)
2025-08-17T12:43:07.5027544Z [command]/usr/bin/tar -xf /home/runner/work/_temp/4f608507-9dbc-4ef8-b182-72bc600e8e14/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-17T12:43:07.8520232Z Cache restored successfully
2025-08-17T12:43:07.8937354Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
