2025-08-17T02:14:09.1874029Z ##[group]Run actions/setup-python@v5
2025-08-17T02:14:09.1874289Z with:
2025-08-17T02:14:09.1874460Z   python-version: 3.11
2025-08-17T02:14:09.1874651Z   cache: pip
2025-08-17T02:14:09.1874857Z   cache-dependency-path: requirements-dev.txt

2025-08-17T02:14:09.1875138Z   check-latest: false
2025-08-17T02:14:09.1875441Z   token: ***
2025-08-17T02:14:09.1875624Z   update-environment: true
2025-08-17T02:14:09.1875837Z   allow-prereleases: false
2025-08-17T02:14:09.1876048Z   freethreaded: false
2025-08-17T02:14:09.1876218Z env:
2025-08-17T02:14:09.1876375Z   PG_USER: postgres
2025-08-17T02:14:09.1876557Z   PG_PASSWORD: pass
2025-08-17T02:14:09.1876737Z   PG_DATABASE: awa
2025-08-17T02:14:09.1876921Z   PG_HOST: localhost
2025-08-17T02:14:09.1877108Z   PG_PORT: 5432
2025-08-17T02:14:09.1877485Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-17T02:14:09.1877876Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-17T02:14:09.1878257Z   DATABASE_URL: ***localhost:5432/awa
2025-08-17T02:14:09.1878479Z   DATA_DIR: /tmp/awa-data
2025-08-17T02:14:09.1878697Z   ENABLE_LIVE: 0
2025-08-17T02:14:09.1878863Z   TESTING: 1
2025-08-17T02:14:09.1879018Z ##[endgroup]
2025-08-17T02:14:09.3522410Z ##[group]Installed versions
2025-08-17T02:14:09.3608907Z Successfully set up CPython (3.11.13)
2025-08-17T02:14:09.3609705Z ##[endgroup]
2025-08-17T02:14:09.3887817Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-17T02:14:11.0479152Z /home/runner/.cache/pip
2025-08-17T02:14:11.1383963Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
2025-08-17T02:14:12.1109237Z Received 203535974 of 203535974 (100.0%), 206.9 MBs/sec
2025-08-17T02:14:12.1111775Z Cache Size: ~194 MB (203535974 B)
2025-08-17T02:14:12.1228495Z [command]/usr/bin/tar -xf /home/runner/work/_temp/79c15717-4c1a-445c-9473-470ea23008a1/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-17T02:14:12.4861256Z Cache restored successfully
2025-08-17T02:14:12.5248973Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
