2025-08-16T23:20:09.5673611Z ##[group]Run actions/setup-python@v5
2025-08-16T23:20:09.5673906Z with:
2025-08-16T23:20:09.5674107Z   python-version: 3.11
2025-08-16T23:20:09.5674324Z   cache: pip
2025-08-16T23:20:09.5674565Z   cache-dependency-path: requirements-dev.txt

2025-08-16T23:20:09.5674863Z   check-latest: false
2025-08-16T23:20:09.5675221Z   token: ***
2025-08-16T23:20:09.5675435Z   update-environment: true
2025-08-16T23:20:09.5675677Z   allow-prereleases: false
2025-08-16T23:20:09.5675896Z   freethreaded: false
2025-08-16T23:20:09.5676096Z env:
2025-08-16T23:20:09.5676281Z   PG_USER: postgres
2025-08-16T23:20:09.5676483Z   PG_PASSWORD: pass
2025-08-16T23:20:09.5676686Z   PG_DATABASE: awa
2025-08-16T23:20:09.5676881Z   PG_HOST: localhost
2025-08-16T23:20:09.5677086Z   PG_PORT: 5432
2025-08-16T23:20:09.5677489Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-16T23:20:09.5677896Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-16T23:20:09.5678291Z   DATABASE_URL: ***localhost:5432/awa
2025-08-16T23:20:09.5678540Z   DATA_DIR: /tmp/awa-data
2025-08-16T23:20:09.5678786Z   ENABLE_LIVE: 0
2025-08-16T23:20:09.5678981Z   TESTING: 1
2025-08-16T23:20:09.5679167Z ##[endgroup]
2025-08-16T23:20:09.7298414Z ##[group]Installed versions
2025-08-16T23:20:09.7421294Z Successfully set up CPython (3.11.13)
2025-08-16T23:20:09.7422513Z ##[endgroup]
2025-08-16T23:20:09.7702019Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-16T23:20:10.0875137Z /home/runner/.cache/pip
2025-08-16T23:20:10.1803773Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
2025-08-16T23:20:11.1213396Z Received 203535974 of 203535974 (100.0%), 214.5 MBs/sec
2025-08-16T23:20:11.1214227Z Cache Size: ~194 MB (203535974 B)
2025-08-16T23:20:11.1241260Z [command]/usr/bin/tar -xf /home/runner/work/_temp/77cc3ee7-b4d3-41e0-974c-fb029bf5a120/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-16T23:20:11.4551567Z Cache restored successfully
2025-08-16T23:20:11.4939663Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
