2025-08-16T21:01:22.9048079Z ##[group]Run actions/setup-python@v5
2025-08-16T21:01:22.9048329Z with:
2025-08-16T21:01:22.9048499Z   python-version: 3.11
2025-08-16T21:01:22.9048682Z   cache: pip
2025-08-16T21:01:22.9048890Z   cache-dependency-path: requirements-dev.txt

2025-08-16T21:01:22.9049152Z   check-latest: false
2025-08-16T21:01:22.9049454Z   token: ***
2025-08-16T21:01:22.9049641Z   update-environment: true
2025-08-16T21:01:22.9049848Z   allow-prereleases: false
2025-08-16T21:01:22.9050045Z   freethreaded: false
2025-08-16T21:01:22.9050217Z env:
2025-08-16T21:01:22.9050371Z   PG_USER: postgres
2025-08-16T21:01:22.9050546Z   PG_PASSWORD: pass
2025-08-16T21:01:22.9050722Z   PG_DATABASE: awa
2025-08-16T21:01:22.9050889Z   PG_HOST: localhost
2025-08-16T21:01:22.9051063Z   PG_PORT: 5432
2025-08-16T21:01:22.9051431Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-16T21:01:22.9051821Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-16T21:01:22.9052183Z   DATABASE_URL: ***localhost:5432/awa
2025-08-16T21:01:22.9052412Z   DATA_DIR: /tmp/awa-data
2025-08-16T21:01:22.9052620Z   ENABLE_LIVE: 0
2025-08-16T21:01:22.9052785Z   TESTING: 1
2025-08-16T21:01:22.9052935Z ##[endgroup]
2025-08-16T21:01:23.0732858Z ##[group]Installed versions
2025-08-16T21:01:23.1304766Z Successfully set up CPython (3.11.13)
2025-08-16T21:01:23.1305474Z ##[endgroup]
2025-08-16T21:01:23.1660231Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-16T21:01:24.8447451Z /home/runner/.cache/pip
2025-08-16T21:01:24.9704755Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
2025-08-16T21:01:25.9593544Z Received 203535974 of 203535974 (100.0%), 205.2 MBs/sec
2025-08-16T21:01:25.9595927Z Cache Size: ~194 MB (203535974 B)
2025-08-16T21:01:25.9708781Z [command]/usr/bin/tar -xf /home/runner/work/_temp/a307b442-841d-4d0d-90f1-9fcfeb876c31/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-16T21:01:26.3285921Z Cache restored successfully
2025-08-16T21:01:26.3678910Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
