2025-08-17T15:24:15.7328532Z ##[group]Run actions/setup-python@v5
2025-08-17T15:24:15.7328815Z with:
2025-08-17T15:24:15.7328994Z   python-version: 3.11
2025-08-17T15:24:15.7329441Z   cache: pip
2025-08-17T15:24:15.7329707Z   cache-dependency-path: requirements-dev.txt

2025-08-17T15:24:15.7329986Z   check-latest: false
2025-08-17T15:24:15.7330293Z   token: ***
2025-08-17T15:24:15.7330484Z   update-environment: true
2025-08-17T15:24:15.7330701Z   allow-prereleases: false
2025-08-17T15:24:15.7330903Z   freethreaded: false
2025-08-17T15:24:15.7331081Z env:
2025-08-17T15:24:15.7331242Z   PG_USER: postgres
2025-08-17T15:24:15.7331422Z   PG_PASSWORD: pass
2025-08-17T15:24:15.7331593Z   PG_DATABASE: awa
2025-08-17T15:24:15.7331768Z   PG_HOST: localhost
2025-08-17T15:24:15.7331949Z   PG_PORT: 5432
2025-08-17T15:24:15.7332365Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-17T15:24:15.7332761Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-17T15:24:15.7333177Z   DATABASE_URL: ***localhost:5432/awa
2025-08-17T15:24:15.7333401Z   DATA_DIR: /tmp/awa-data
2025-08-17T15:24:15.7333629Z   ENABLE_LIVE: 0
2025-08-17T15:24:15.7333801Z   TESTING: 1
2025-08-17T15:24:15.7333956Z ##[endgroup]
2025-08-17T15:24:15.8994931Z ##[group]Installed versions
2025-08-17T15:24:15.9561044Z Successfully set up CPython (3.11.13)
2025-08-17T15:24:15.9561729Z ##[endgroup]
2025-08-17T15:24:15.9880925Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-17T15:24:17.7043729Z /home/runner/.cache/pip
2025-08-17T15:24:17.8046076Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-2005571a326e80fd181d633d96bfcc1ae8cb53ffd7b38d40aba6418cea7f5ab1
2025-08-17T15:24:18.7765079Z Received 230957298 of 230957298 (100.0%), 236.8 MBs/sec
2025-08-17T15:24:18.7767725Z Cache Size: ~220 MB (230957298 B)
2025-08-17T15:24:18.7805562Z [command]/usr/bin/tar -xf /home/runner/work/_temp/a54ee590-f1b6-43ea-8261-bd27b7a1c140/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-17T15:24:19.1954666Z Cache restored successfully
2025-08-17T15:24:19.2389462Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-37c9ce054bf8aec7fb9f1b24cb0b7760d658659de5ba6816a1006b9693ca1c25
