2025-08-17T13:19:36.4471551Z ##[group]Run actions/setup-python@v5
2025-08-17T13:19:36.4472090Z with:
2025-08-17T13:19:36.4472282Z   python-version: 3.11
2025-08-17T13:19:36.4472482Z   cache: pip
2025-08-17T13:19:36.4472690Z   cache-dependency-path: requirements-dev.txt

2025-08-17T13:19:36.4472968Z   check-latest: false
2025-08-17T13:19:36.4473270Z   token: ***
2025-08-17T13:19:36.4473461Z   update-environment: true
2025-08-17T13:19:36.4473683Z   allow-prereleases: false
2025-08-17T13:19:36.4473886Z   freethreaded: false
2025-08-17T13:19:36.4474068Z env:
2025-08-17T13:19:36.4474231Z   PG_USER: postgres
2025-08-17T13:19:36.4474424Z   PG_PASSWORD: pass
2025-08-17T13:19:36.4474601Z   PG_DATABASE: awa
2025-08-17T13:19:36.4474778Z   PG_HOST: localhost
2025-08-17T13:19:36.4474954Z   PG_PORT: 5432
2025-08-17T13:19:36.4475345Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-17T13:19:36.4475734Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-17T13:19:36.4476167Z   DATABASE_URL: ***localhost:5432/awa
2025-08-17T13:19:36.4476400Z   DATA_DIR: /tmp/awa-data
2025-08-17T13:19:36.4476651Z   ENABLE_LIVE: 0
2025-08-17T13:19:36.4477012Z   TESTING: 1
2025-08-17T13:19:36.4477176Z ##[endgroup]
2025-08-17T13:19:36.6105362Z ##[group]Installed versions
2025-08-17T13:19:36.6228626Z Successfully set up CPython (3.11.13)
2025-08-17T13:19:36.6229418Z ##[endgroup]
2025-08-17T13:19:36.6514999Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-17T13:19:37.7860816Z /home/runner/.cache/pip
2025-08-17T13:19:37.9109337Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
2025-08-17T13:19:38.9693694Z Received 203535974 of 203535974 (100.0%), 194.3 MBs/sec
2025-08-17T13:19:38.9695838Z Cache Size: ~194 MB (203535974 B)
2025-08-17T13:19:38.9737297Z [command]/usr/bin/tar -xf /home/runner/work/_temp/d287c574-3b40-4352-a292-16434fb859db/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-17T13:19:39.3650186Z Cache restored successfully
2025-08-17T13:19:39.4033525Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
