2025-08-16T20:39:13.1966862Z ##[group]Run actions/setup-python@v5
2025-08-16T20:39:13.1967131Z with:
2025-08-16T20:39:13.1967306Z   python-version: 3.11
2025-08-16T20:39:13.1967499Z   cache: pip
2025-08-16T20:39:13.1967709Z   cache-dependency-path: requirements-dev.txt

2025-08-16T20:39:13.1968207Z   check-latest: false
2025-08-16T20:39:13.1968525Z   token: ***
2025-08-16T20:39:13.1968719Z   update-environment: true
2025-08-16T20:39:13.1968939Z   allow-prereleases: false
2025-08-16T20:39:13.1969141Z   freethreaded: false
2025-08-16T20:39:13.1969319Z env:
2025-08-16T20:39:13.1969491Z   PG_USER: postgres
2025-08-16T20:39:13.1969676Z   PG_PASSWORD: pass
2025-08-16T20:39:13.1969851Z   PG_DATABASE: awa
2025-08-16T20:39:13.1970029Z   PG_HOST: localhost
2025-08-16T20:39:13.1970205Z   PG_PORT: 5432
2025-08-16T20:39:13.1970589Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-16T20:39:13.1970978Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-16T20:39:13.1971356Z   DATABASE_URL: ***localhost:5432/awa
2025-08-16T20:39:13.1971580Z   DATA_DIR: /tmp/awa-data
2025-08-16T20:39:13.1971812Z   ENABLE_LIVE: 0
2025-08-16T20:39:13.1971987Z   TESTING: 1
2025-08-16T20:39:13.1972146Z ##[endgroup]
2025-08-16T20:39:13.3600599Z ##[group]Installed versions
2025-08-16T20:39:13.3703751Z Successfully set up CPython (3.11.13)
2025-08-16T20:39:13.3704551Z ##[endgroup]
2025-08-16T20:39:13.4018433Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-16T20:39:14.8306149Z /home/runner/.cache/pip
2025-08-16T20:39:14.9172244Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
2025-08-16T20:39:15.9385216Z Received 203535974 of 203535974 (100.0%), 196.5 MBs/sec
2025-08-16T20:39:15.9387850Z Cache Size: ~194 MB (203535974 B)
2025-08-16T20:39:15.9425633Z [command]/usr/bin/tar -xf /home/runner/work/_temp/d5fcfe10-39ee-420e-87f3-451cd364f47a/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-16T20:39:16.3034442Z Cache restored successfully
2025-08-16T20:39:16.3443948Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
