2025-08-17T12:50:03.2067628Z ##[group]Run actions/setup-python@v5
2025-08-17T12:50:03.2067969Z with:
2025-08-17T12:50:03.2068154Z   python-version: 3.11
2025-08-17T12:50:03.2068360Z   cache: pip
2025-08-17T12:50:03.2068579Z   cache-dependency-path: requirements-dev.txt

2025-08-17T12:50:03.2068858Z   check-latest: false
2025-08-17T12:50:03.2069221Z   token: ***
2025-08-17T12:50:03.2069411Z   update-environment: true
2025-08-17T12:50:03.2069625Z   allow-prereleases: false
2025-08-17T12:50:03.2069832Z   freethreaded: false
2025-08-17T12:50:03.2070007Z env:
2025-08-17T12:50:03.2070198Z   PG_USER: postgres
2025-08-17T12:50:03.2070379Z   PG_PASSWORD: pass
2025-08-17T12:50:03.2070550Z   PG_DATABASE: awa
2025-08-17T12:50:03.2070724Z   PG_HOST: localhost
2025-08-17T12:50:03.2070897Z   PG_PORT: 5432
2025-08-17T12:50:03.2071272Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-17T12:50:03.2071644Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-17T12:50:03.2072030Z   DATABASE_URL: ***localhost:5432/awa
2025-08-17T12:50:03.2072248Z   DATA_DIR: /tmp/awa-data
2025-08-17T12:50:03.2072559Z   ENABLE_LIVE: 0
2025-08-17T12:50:03.2072745Z   TESTING: 1
2025-08-17T12:50:03.2072910Z ##[endgroup]
2025-08-17T12:50:03.3711441Z ##[group]Installed versions
2025-08-17T12:50:03.3820379Z Successfully set up CPython (3.11.13)
2025-08-17T12:50:03.3821795Z ##[endgroup]
2025-08-17T12:50:03.4295251Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-17T12:50:05.1745313Z /home/runner/.cache/pip
2025-08-17T12:50:05.2690443Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
2025-08-17T12:50:06.2160198Z Received 203535974 of 203535974 (100.0%), 215.2 MBs/sec
2025-08-17T12:50:06.2162848Z Cache Size: ~194 MB (203535974 B)
2025-08-17T12:50:06.2213902Z [command]/usr/bin/tar -xf /home/runner/work/_temp/15d8ce4e-9c9b-4e9c-be64-089056fb534d/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-17T12:50:06.5762844Z Cache restored successfully
2025-08-17T12:50:06.6154009Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
