2025-08-17T03:01:15.3655056Z ##[group]Run actions/setup-python@v5
2025-08-17T03:01:15.3655333Z with:
2025-08-17T03:01:15.3655516Z   python-version: 3.11
2025-08-17T03:01:15.3655712Z   cache: pip
2025-08-17T03:01:15.3655924Z   cache-dependency-path: requirements-dev.txt

2025-08-17T03:01:15.3656199Z   check-latest: false
2025-08-17T03:01:15.3656507Z   token: ***
2025-08-17T03:01:15.3656701Z   update-environment: true
2025-08-17T03:01:15.3656920Z   allow-prereleases: false
2025-08-17T03:01:15.3657125Z   freethreaded: false
2025-08-17T03:01:15.3657305Z env:
2025-08-17T03:01:15.3657468Z   PG_USER: postgres
2025-08-17T03:01:15.3657907Z   PG_PASSWORD: pass
2025-08-17T03:01:15.3658118Z   PG_DATABASE: awa
2025-08-17T03:01:15.3658300Z   PG_HOST: localhost
2025-08-17T03:01:15.3658480Z   PG_PORT: 5432
2025-08-17T03:01:15.3658889Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-17T03:01:15.3659277Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-17T03:01:15.3659675Z   DATABASE_URL: ***localhost:5432/awa
2025-08-17T03:01:15.3659907Z   DATA_DIR: /tmp/awa-data
2025-08-17T03:01:15.3660133Z   ENABLE_LIVE: 0
2025-08-17T03:01:15.3660304Z   TESTING: 1
2025-08-17T03:01:15.3660461Z ##[endgroup]
2025-08-17T03:01:15.5305685Z ##[group]Installed versions
2025-08-17T03:01:15.5846840Z Successfully set up CPython (3.11.13)
2025-08-17T03:01:15.5847893Z ##[endgroup]
2025-08-17T03:01:15.6237448Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-17T03:01:17.2354440Z /home/runner/.cache/pip
2025-08-17T03:01:17.3393299Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
2025-08-17T03:01:18.3410238Z Received 203535974 of 203535974 (100.0%), 205.6 MBs/sec
2025-08-17T03:01:18.3412038Z Cache Size: ~194 MB (203535974 B)
2025-08-17T03:01:18.3534165Z [command]/usr/bin/tar -xf /home/runner/work/_temp/d92abbb8-8693-4e65-bf21-84a5a84b5c7b/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-17T03:01:18.7255895Z Cache restored successfully
2025-08-17T03:01:18.7648023Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
