2025-08-17T01:48:16.6410190Z ##[group]Run actions/setup-python@v5
2025-08-17T01:48:16.6410458Z with:
2025-08-17T01:48:16.6410642Z   python-version: 3.11
2025-08-17T01:48:16.6410842Z   cache: pip
2025-08-17T01:48:16.6411052Z   cache-dependency-path: requirements-dev.txt

2025-08-17T01:48:16.6411333Z   check-latest: false
2025-08-17T01:48:16.6411635Z   token: ***
2025-08-17T01:48:16.6411825Z   update-environment: true
2025-08-17T01:48:16.6412040Z   allow-prereleases: false
2025-08-17T01:48:16.6412457Z   freethreaded: false
2025-08-17T01:48:16.6412662Z env:
2025-08-17T01:48:16.6412827Z   PG_USER: postgres
2025-08-17T01:48:16.6413011Z   PG_PASSWORD: pass
2025-08-17T01:48:16.6413186Z   PG_DATABASE: awa
2025-08-17T01:48:16.6413362Z   PG_HOST: localhost
2025-08-17T01:48:16.6413537Z   PG_PORT: 5432
2025-08-17T01:48:16.6413924Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-17T01:48:16.6414306Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-17T01:48:16.6414704Z   DATABASE_URL: ***localhost:5432/awa
2025-08-17T01:48:16.6414937Z   DATA_DIR: /tmp/awa-data
2025-08-17T01:48:16.6415168Z   ENABLE_LIVE: 0
2025-08-17T01:48:16.6415341Z   TESTING: 1
2025-08-17T01:48:16.6415499Z ##[endgroup]
2025-08-17T01:48:16.8038903Z ##[group]Installed versions
2025-08-17T01:48:16.8117491Z Successfully set up CPython (3.11.13)
2025-08-17T01:48:16.8118302Z ##[endgroup]
2025-08-17T01:48:16.8407331Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-17T01:48:17.0411397Z /home/runner/.cache/pip
2025-08-17T01:48:17.1391179Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
2025-08-17T01:48:18.1798700Z Received 203535974 of 203535974 (100.0%), 197.5 MBs/sec
2025-08-17T01:48:18.1805270Z Cache Size: ~194 MB (203535974 B)
2025-08-17T01:48:18.1944899Z [command]/usr/bin/tar -xf /home/runner/work/_temp/94374f35-5bf6-494d-aa88-dd285dbb3eb0/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-17T01:48:18.5667331Z Cache restored successfully
2025-08-17T01:48:18.6080132Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
