2025-08-17T00:13:06.5981227Z ##[group]Run actions/setup-python@v5
2025-08-17T00:13:06.5981503Z with:
2025-08-17T00:13:06.5981691Z   python-version: 3.11
2025-08-17T00:13:06.5981882Z   cache: pip
2025-08-17T00:13:06.5982107Z   cache-dependency-path: requirements-dev.txt

2025-08-17T00:13:06.5982398Z   check-latest: false
2025-08-17T00:13:06.5982704Z   token: ***
2025-08-17T00:13:06.5982898Z   update-environment: true
2025-08-17T00:13:06.5983115Z   allow-prereleases: false
2025-08-17T00:13:06.5983325Z   freethreaded: false
2025-08-17T00:13:06.5983504Z env:
2025-08-17T00:13:06.5983666Z   PG_USER: postgres
2025-08-17T00:13:06.5983854Z   PG_PASSWORD: pass
2025-08-17T00:13:06.5984031Z   PG_DATABASE: awa
2025-08-17T00:13:06.5984213Z   PG_HOST: localhost
2025-08-17T00:13:06.5984391Z   PG_PORT: 5432
2025-08-17T00:13:06.5984771Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-17T00:13:06.5985168Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-17T00:13:06.5985554Z   DATABASE_URL: ***localhost:5432/awa
2025-08-17T00:13:06.5985986Z   DATA_DIR: /tmp/awa-data
2025-08-17T00:13:06.5986210Z   ENABLE_LIVE: 0
2025-08-17T00:13:06.5986382Z   TESTING: 1
2025-08-17T00:13:06.5986542Z ##[endgroup]
2025-08-17T00:13:06.7658708Z ##[group]Installed versions
2025-08-17T00:13:06.7780783Z Successfully set up CPython (3.11.13)
2025-08-17T00:13:06.7781614Z ##[endgroup]
2025-08-17T00:13:06.8188368Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-17T00:13:08.7759296Z /home/runner/.cache/pip
2025-08-17T00:13:08.8911541Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
2025-08-17T00:13:09.9152738Z Received 203535974 of 203535974 (100.0%), 197.9 MBs/sec
2025-08-17T00:13:09.9155200Z Cache Size: ~194 MB (203535974 B)
2025-08-17T00:13:09.9192775Z [command]/usr/bin/tar -xf /home/runner/work/_temp/debca6d1-82d0-4a7e-b263-4a8b1526f5e4/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-17T00:13:10.2525583Z Cache restored successfully
2025-08-17T00:13:10.2913521Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-dee7c0c28332ec2ebb5d2650fb0d2cfddf025b3b0e96b0c826645ad2cb717961
