2025-08-17T16:39:12.8150047Z ##[group]Run actions/setup-python@v5
2025-08-17T16:39:12.8150336Z with:
2025-08-17T16:39:12.8150527Z   python-version: 3.11
2025-08-17T16:39:12.8150735Z   cache: pip
2025-08-17T16:39:12.8150966Z   cache-dependency-path: requirements-dev.txt

2025-08-17T16:39:12.8151252Z   check-latest: false
2025-08-17T16:39:12.8151580Z   token: ***
2025-08-17T16:39:12.8151767Z   update-environment: true
2025-08-17T16:39:12.8151990Z   allow-prereleases: false
2025-08-17T16:39:12.8152192Z   freethreaded: false
2025-08-17T16:39:12.8152378Z env:
2025-08-17T16:39:12.8152541Z   PG_USER: postgres
2025-08-17T16:39:12.8152722Z   PG_PASSWORD: pass
2025-08-17T16:39:12.8152907Z   PG_DATABASE: awa
2025-08-17T16:39:12.8153080Z   PG_HOST: localhost
2025-08-17T16:39:12.8153264Z   PG_PORT: 5432
2025-08-17T16:39:12.8153646Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-17T16:39:12.8154043Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-17T16:39:12.8154431Z   DATABASE_URL: ***localhost:5432/awa
2025-08-17T16:39:12.8154681Z   DATA_DIR: /tmp/awa-data
2025-08-17T16:39:12.8154916Z   ENABLE_LIVE: 0
2025-08-17T16:39:12.8155090Z   TESTING: 1
2025-08-17T16:39:12.8155259Z ##[endgroup]
2025-08-17T16:39:12.9800779Z ##[group]Installed versions
2025-08-17T16:39:13.0192749Z Successfully set up CPython (3.11.13)
2025-08-17T16:39:13.0193559Z ##[endgroup]
2025-08-17T16:39:13.0500909Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-17T16:39:14.3684858Z /home/runner/.cache/pip
2025-08-17T16:39:14.4874993Z Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-842a859a37b6f31d35b1262d499b1acd0270bca26490137bed88679f7bc0eea4
2025-08-17T16:39:15.5801556Z Received 248873328 of 248873328 (100.0%), 224.8 MBs/sec
2025-08-17T16:39:15.5803711Z Cache Size: ~237 MB (248873328 B)
2025-08-17T16:39:15.5843100Z [command]/usr/bin/tar -xf /home/runner/work/_temp/fdb883be-d2cf-4666-8e3c-e2738ad0b411/cache.tzst -P -C /home/runner/work/AWA-App/AWA-App --use-compress-program unzstd
2025-08-17T16:39:16.0467638Z Cache restored successfully
2025-08-17T16:39:16.0939913Z Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.13-pip-2005571a326e80fd181d633d96bfcc1ae8cb53ffd7b38d40aba6418cea7f5ab1
