2025-08-20T18:14:52.1292100Z ##[group]Run pytest tests/migrations/test_migration_roundtrip.py -q --cov=services --cov-append --cov-fail-under=0
2025-08-20T18:14:52.1292961Z [36;1mpytest tests/migrations/test_migration_roundtrip.py -q --cov=services --cov-append --cov-fail-under=0[0m
2025-08-20T18:14:52.1332822Z shell: /usr/bin/bash -e {0}
2025-08-20T18:14:52.1333055Z env:
2025-08-20T18:14:52.1333226Z   PG_USER: postgres
2025-08-20T18:14:52.1333427Z   PG_PASSWORD: pass
2025-08-20T18:14:52.1333619Z   PG_DATABASE: awa
2025-08-20T18:14:52.1333804Z   PG_HOST: localhost
2025-08-20T18:14:52.1333991Z   PG_PORT: 5432
2025-08-20T18:14:52.1334488Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-20T18:14:52.1334895Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-20T18:14:52.1335286Z   DATABASE_URL: ***localhost:5432/awa
2025-08-20T18:14:52.1335526Z   DATA_DIR: /tmp/awa-data
2025-08-20T18:14:52.1335732Z   ENABLE_LIVE: 0
2025-08-20T18:14:52.1335912Z   TESTING: 1
2025-08-20T18:14:52.1336149Z   pythonLocation: /opt/hostedtoolcache/Python/3.11.13/x64
2025-08-20T18:14:52.1336579Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.13/x64/lib/pkgconfig
2025-08-20T18:14:52.1336978Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.13/x64
2025-08-20T18:14:52.1337333Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.13/x64
2025-08-20T18:14:52.1337688Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.13/x64
2025-08-20T18:14:52.1338038Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.13/x64/lib
2025-08-20T18:14:52.1338335Z ##[endgroup]
2025-08-20T18:14:54.2486801Z 
2025-08-20T18:14:54.2487507Z ================================ tests coverage ================================
2025-08-20T18:14:54.2488440Z _______________ coverage: platform linux, python 3.11.13-final-0 _______________
2025-08-20T18:14:54.2488819Z 
2025-08-20T18:14:54.2488959Z Coverage XML written to file coverage.xml
2025-08-20T18:14:54.3723425Z ##[error]Process completed with exit code 5.
