2025-08-26T10:12:30.5574980Z ##[group]Run npm ci
2025-08-26T10:12:30.5575243Z [36;1mnpm ci[0m
2025-08-26T10:12:30.5616345Z shell: /usr/bin/bash -e {0}
2025-08-26T10:12:30.5616584Z env:
2025-08-26T10:12:30.5616798Z   REDIS_URL: redis://localhost:6379/0
2025-08-26T10:12:30.5617074Z   RATE_LIMIT_DEFAULT: 100/minute
2025-08-26T10:12:30.5617425Z   TRUST_X_FORWARDED: 1
2025-08-26T10:12:30.5617630Z   PG_USER: postgres
2025-08-26T10:12:30.5617840Z   PG_PASSWORD: pass
2025-08-26T10:12:30.5618033Z   PG_DATABASE: awa
2025-08-26T10:12:30.5618224Z   PG_HOST: localhost
2025-08-26T10:12:30.5618422Z   PG_PORT: 5432
2025-08-26T10:12:30.5618850Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-26T10:12:30.5619458Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-26T10:12:30.5619857Z   DATABASE_URL: ***localhost:5432/awa
2025-08-26T10:12:30.5620110Z   DATA_DIR: /tmp/awa-data
2025-08-26T10:12:30.5620325Z   ENABLE_LIVE: 0
2025-08-26T10:12:30.5620501Z   TESTING: 1
2025-08-26T10:12:30.5620745Z   pythonLocation: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-26T10:12:30.5621188Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.11/x64/lib/pkgconfig
2025-08-26T10:12:30.5621571Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-26T10:12:30.5621942Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-26T10:12:30.5622298Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-26T10:12:30.5622652Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.11/x64/lib
2025-08-26T10:12:30.5622955Z ##[endgroup]
2025-08-26T10:13:46.6514288Z npm error code E429
2025-08-26T10:13:46.6514967Z npm error 429 Too Many Requests - GET https://registry.npmjs.org/zod/-/zod-3.25.76.tgz
2025-08-26T10:13:46.6536301Z npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-08-26T10_12_30_627Z-debug-0.log
2025-08-26T10:13:46.6792915Z ##[error]Process completed with exit code 1.
